### ISSUE TITLE
dockerify trac-hub

### ISSUE THREAD

**Issue by bwl21** [mavam/trac-hub#26]
First of all I need to express that **trac-hub is awesom**e. After spending some days with tracboat and other scripts this is the first stuff which ended in promising results at github (maybe because it is written ruby :-)

This morning I played with trac-hub. I used docker for that:

```Dockerfile
FROM ruby:2.5

# throw errors if Gemfile has been modified since Gemfile.lock
RUN bundle config --global frozen 1

WORKDIR /usr/src/app

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

ENTRYPOINT cd /usr/src/myapp/trac-hub && bash

```

I start it with docker-compose

```
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

 trac-hub:
    image: bwl21/trac-hub
    build: trac-hub

    restart: unless-stopped

    volumes:
      - .:/usr/src/myapp
      - /Users/beweiche/gitlab/data:/var/opt/gitlab
    links:
      - mysql
    depends_on:
      - mysql
```

Inovoke as 

```invocation
docker-compose run --rm trac-hub
```
